# Generated by Django 4.1.5 on 2023-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificaGenerale',
            fields=[
                ('posizione', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_squadra', models.CharField(max_length=200)),
                ('totale_punti', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'classifica generale',
                'db_table': 'classifica_generale',
            },
        ),
        migrations.CreateModel(
            name='ClassificaPerLega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField()),
                ('lega_id', models.IntegerField()),
                ('nome_lega', models.CharField(max_length=100)),
                ('nome_squadra', models.CharField(max_length=200)),
                ('totale_punti', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'classifica per lega',
                'db_table': 'classifica_per_lega',
            },
        ),
        migrations.CreateModel(
            name='ClassificaPolitico',
            fields=[
                ('posizione', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_politico', models.CharField(max_length=200)),
                ('totale_punti', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'classifica politici',
                'db_table': 'classifica_politico',
            },
        ),
    ]
