# Generated by Django 4.1.4 on 2022-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name_plural': 'classifica per lega',
                'db_table': 'lega',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='classificagenerale',
            options={'managed': False, 'verbose_name_plural': 'classifica generale'},
        ),
        migrations.AlterModelOptions(
            name='classificaperlega',
            options={'managed': False, 'verbose_name_plural': 'classifica per lega'},
        ),
        migrations.AlterModelOptions(
            name='classificapolitico',
            options={'managed': False, 'verbose_name_plural': 'classifica politici'},
        ),
        migrations.AlterModelTable(
            name='classificaperlega',
            table='v_classifica_per_lega',
        ),
    ]
