# Generated by Django 4.1.5 on 2023-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0002_squadrapunti_alter_classificagenerale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadrapunti',
            options={'ordering': ('puntata_numero',), 'verbose_name_plural': 'punti squadra'},
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='squadra_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificaperlega',
            name='squadra_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
