# Generated by Django 4.1.4 on 2022-12-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0002_lega_alter_classificagenerale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificaperlega',
            options={'managed': False, 'ordering': ['lega__name', 'posizione'], 'verbose_name_plural': 'classifica per lega'},
        ),
        migrations.AlterModelOptions(
            name='lega',
            options={'managed': False, 'verbose_name_plural': 'leghe'},
        ),
    ]
