# Generated by Django 4.1.4 on 2022-12-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0003_alter_classificaperlega_options_alter_lega_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lega',
        ),
    ]
