# Generated by Django 4.1.5 on 2023-01-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0005_alter_classificagenerale_leader_politico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificagenerale',
            name='creato_il',
            field=models.DateTimeField(null=True),
        ),
    ]
