# Generated by Django 4.1.5 on 2023-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0006_classificagenerale_creato_il'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadrapunti',
            options={'ordering': ('-puntata_numero',), 'verbose_name_plural': 'punti squadra'},
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='fanfani',
            field=models.IntegerField(default=0),
        ),
    ]
