# Generated by Django 4.1.5 on 2023-01-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0007_alter_squadrapunti_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadrapunti',
            options={'ordering': ('-puntata_numero', '-id'), 'verbose_name_plural': 'punti squadra'},
        ),
    ]
