# Generated by Django 4.1.5 on 2023-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0008_alter_squadrapunti_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificagenerale',
            name='codice_squadra',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
