# Generated by Django 4.1.6 on 2023-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0009_classificagenerale_codice_squadra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunteggioPuntata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntata_numero', models.IntegerField()),
                ('puntata_data', models.DateTimeField(auto_now_add=True)),
                ('politico_name', models.CharField(max_length=200)),
                ('punti', models.IntegerField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'punteggi',
                'db_table': 'punteggio puntata',
                'ordering': ('-creato_il',),
            },
        ),
    ]
