# Generated by Django 4.1.6 on 2023-02-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0010_punteggiopuntata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='punteggiopuntata',
            table='punteggio_puntata',
        ),
    ]
