# Generated by Django 4.1.7 on 2023-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0011_alter_punteggiopuntata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_leader_politico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificagenerale',
            name='totale_politico_9',
            field=models.IntegerField(default=0),
        ),
    ]
