# Generated by Django 4.2.2 on 2023-06-18 10:38

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_classifiche_app', '0013_classificagenerale_site_classificaperlega_site_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classificagenerale',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classificaperlega',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classificapolitico',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='punteggiopuntata',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
