# Generated by Django 4.1.3 on 2022-11-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fanfani', models.IntegerField()),
            ],
            options={
                'db_table': 'carica',
            },
        ),
        migrations.CreateModel(
            name='Lega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lega',
            },
        ),
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=200)),
                ('carica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.carica')),
            ],
            options={
                'db_table': 'politico',
            },
        ),
        migrations.CreateModel(
            name='Puntata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'puntata',
            },
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('leader_politico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.politico')),
                ('number_10_politico', models.ForeignKey(db_column='10_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_10_politico', to='fc_gestione_app.politico')),
                ('number_11_politico', models.ForeignKey(db_column='11_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_12_politico', to='fc_gestione_app.politico')),
                ('number_1_politico', models.ForeignKey(db_column='1_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_1_politico', to='fc_gestione_app.politico')),
                ('number_2_politico', models.ForeignKey(db_column='2_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_2_politico', to='fc_gestione_app.politico')),
                ('number_3_politico', models.ForeignKey(db_column='3_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_3_politico', to='fc_gestione_app.politico')),
                ('number_4_politico', models.ForeignKey(db_column='4_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_4_politico', to='fc_gestione_app.politico')),
                ('number_5_politico', models.ForeignKey(db_column='5_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_5_politico', to='fc_gestione_app.politico')),
                ('number_6_politico', models.ForeignKey(db_column='6_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_6_politico', to='fc_gestione_app.politico')),
                ('number_7_politico', models.ForeignKey(db_column='7_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_7_politico', to='fc_gestione_app.politico')),
                ('number_8_politico', models.ForeignKey(db_column='8_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_8_politico', to='fc_gestione_app.politico')),
                ('number_9_politico', models.ForeignKey(db_column='9_politico_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='number_9_politico', to='fc_gestione_app.politico')),
            ],
            options={
                'db_table': 'squadra',
            },
        ),
        migrations.CreateModel(
            name='Punteggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti', models.IntegerField()),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.politico')),
                ('puntata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.puntata')),
            ],
            options={
                'db_table': 'punteggio',
            },
        ),
        migrations.CreateModel(
            name='LegaSquadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.lega')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fc_gestione_app.squadra')),
            ],
            options={
                'db_table': 'lega_squadra',
            },
        ),
    ]
