# Generated by Django 4.1.3 on 2022-11-30 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fc_gestione_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carica',
            options={'verbose_name_plural': 'cariche'},
        ),
        migrations.AlterModelOptions(
            name='lega',
            options={'verbose_name_plural': 'leghe'},
        ),
        migrations.AlterModelOptions(
            name='legasquadra',
            options={'verbose_name_plural': 'leghe squadre'},
        ),
        migrations.AlterModelOptions(
            name='politico',
            options={'verbose_name_plural': 'politici'},
        ),
        migrations.AlterModelOptions(
            name='puntata',
            options={'verbose_name_plural': 'puntate'},
        ),
        migrations.AlterModelOptions(
            name='punteggio',
            options={'verbose_name_plural': 'punteggi'},
        ),
        migrations.AlterModelOptions(
            name='squadra',
            options={'verbose_name_plural': 'squadre'},
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='user_id',
        ),
        migrations.AddField(
            model_name='squadra',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carica',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lega',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='politico',
            name='nominativo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='legasquadra',
            unique_together={('lega', 'squadra')},
        ),
    ]
