# Generated by Django 4.1.3 on 2022-11-30 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fc_gestione_app', '0002_alter_carica_options_alter_lega_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
