# Generated by Django 4.1.3 on 2022-11-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0004_remove_carica_nome_carica_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lega',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='politico',
            name='nominativo',
        ),
        migrations.AddField(
            model_name='lega',
            name='name',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politico',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='nomimativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadra',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='nomimativo'),
            preserve_default=False,
        ),
    ]
