# Generated by Django 4.1.3 on 2022-12-02 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fc_gestione_app', '0005_remove_lega_nome_remove_politico_nominativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
