# Generated by Django 4.1.3 on 2022-12-03 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0006_alter_squadra_utente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legasquadra',
            options={'verbose_name_plural': 'leghe - squadre'},
        ),
        migrations.AddField(
            model_name='punteggio',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='nomimativo'),
            preserve_default=False,
        ),
    ]
