# Generated by Django 4.1.3 on 2022-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0008_alter_punteggio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadra',
            name='punti',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lega',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nome'),
        ),
    ]
