# Generated by Django 4.1.4 on 2022-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0012_rename_punti_bonus_squarda_squadra_punti_bonus_squadra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politico',
            name='fanfani',
            field=models.IntegerField(default=0),
        ),
    ]
