# Generated by Django 4.1.4 on 2022-12-17 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0013_politico_fanfani'),
    ]

    operations = [
        migrations.AddField(
            model_name='carica',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carica',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lega',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lega',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legasquadra',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='legasquadra',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politico',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='politico',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntata',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puntata',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punteggio',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadra',
            name='aggiornato_id',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='squadra',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
