# Generated by Django 4.1.4 on 2022-12-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0015_alter_carica_name_alter_lega_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carica',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='lega',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='legasquadra',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='politico',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='puntata',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='punteggio',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
        migrations.RenameField(
            model_name='squadra',
            old_name='aggiornato_id',
            new_name='aggiornato_il',
        ),
    ]
