# Generated by Django 4.1.4 on 2022-12-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fc_gestione_app', '0016_rename_aggiornato_id_carica_aggiornato_il_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
