# Generated by Django 4.1.5 on 2023-01-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0019_alter_legasquadra_lega_alter_legasquadra_squadra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carica',
            options={'ordering': ('-fanfani',), 'verbose_name_plural': 'cariche'},
        ),
        migrations.AlterModelOptions(
            name='lega',
            options={'ordering': ('name',), 'verbose_name_plural': 'leghe'},
        ),
        migrations.AlterModelOptions(
            name='legasquadra',
            options={'ordering': ('lega__name', 'squadra__name'), 'verbose_name_plural': 'leghe - squadre'},
        ),
        migrations.AlterModelOptions(
            name='politico',
            options={'ordering': ('name',), 'verbose_name_plural': 'politici'},
        ),
        migrations.AlterModelOptions(
            name='puntata',
            options={'ordering': ('-numero',), 'verbose_name_plural': 'puntate'},
        ),
        migrations.AlterModelOptions(
            name='punteggio',
            options={'ordering': ('-puntata__numero', '-aggiornato_il'), 'verbose_name_plural': 'punteggi'},
        ),
        migrations.AlterModelOptions(
            name='squadra',
            options={'ordering': ('creato_il',), 'verbose_name_plural': 'squadre'},
        ),
    ]
