# Generated by Django 4.1.7 on 2023-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0020_alter_carica_options_alter_lega_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntata',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
