# Generated by Django 4.1.7 on 2023-02-25 12:26

from django.db import migrations

def update_puntata_data(apps, schema_editor):
    # aggiorna l'ora di inizio delle puntate già salvate alle 21:15
    Puntata = apps.get_model('fc_gestione_app', 'Puntata')
    for puntata in Puntata.objects.all():
        puntata.data = puntata.data.replace(hour=21,minute=15,second=0)
        puntata.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0021_alter_puntata_data'),
    ]

    operations = [
         migrations.RunPython(update_puntata_data, reverse_code=migrations.RunPython.noop),
    ]
