# Generated by Django 4.1.7 on 2023-03-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    def null_user_squadra(apps, schema_editor):
        # aggiorna l'ora di inizio delle puntate già salvate alle 21:15
        Squadra = apps.get_model('fc_gestione_app', 'Squadra')
        for squadra in Squadra.objects.all():
            squadra.utente = None
            squadra.save()

    dependencies = [
        ('fc_gestione_app', '0022_update_time_puntata_data'),
    ]

    operations = [
         migrations.RunPython(null_user_squadra, reverse_code=migrations.RunPython.noop),
    ]
