# Generated by Django 4.2.2 on 2023-06-18 10:38

from django.db import migrations
import fc_gestione_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_gestione_app', '0024_lega_site_politico_site_puntata_site_squadra_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lega',
            managers=[
                ('objects', fc_gestione_app.models.LegaManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='politico',
            managers=[
                ('objects', fc_gestione_app.models.PoliticoManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='puntata',
            managers=[
                ('objects', fc_gestione_app.models.PuntataManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='squadra',
            managers=[
                ('objects', fc_gestione_app.models.SquadraManager()),
            ],
        ),
    ]
